spring.application.name=jobs

spring.data.mongodb.uri=mongodb+srv://roghit_DB:rootDB@springdb.wjtmpas.mongodb.net/?appName=springDB
spring.data.mongodb.database=LaunchPadCareersDB

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.mongodb=DEBUG
debug=true

logging.level.root=INFO
logging.file.name=app.log